version: '2'
services:
    mysql:
        image: mariadb:10.4
        container_name: mysql
        volumes:
        - ./db:/var/lib/mysql/
        - ./logs:/var/log/mysql/
        ports:
        - 3306:3306
        environment:
        - MYSQL_ROOT_PASSWORD=12345678a
        restart: always
    #      networks:
    #        - host
